unstable_features = true
max_width = 120
edition = "2024"
use_small_heuristics = "Max"
fn_params_layout = "Compressed"
indent_style = "Visual"
match_block_trailing_comma = true
overflow_delimited_expr = true
trailing_comma = "Never"
struct_field_align_threshold = 20
newline_style = "Unix"
